<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Index</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
	<style>
		html,
		body {
			height: 100%;
		}
	</style>
</head>
<body>
	<?php include(__DIR__ . '/Navbar.phtml'); ?>
</body>
</html>