<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Me</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
	<style>
		html,
		body {
			height: 100%;
		}
		.main {
			display: flex;
			align-items: center;
			justify-content: center;
			padding-top: 40px;
			padding-bottom: 40px;
			background-color: #f5f5f5;
		}
	</style>
</head>
<body>
	<?php include(__DIR__ . '/Navbar.phtml'); ?>
	<div class="main">
		<pre><?php print_r($user); ?></pre>
	</div>
</body>
</html>