<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Notice</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
	<style>
		html,
		body {
			height: 100%;
		}
		.notice {
			width: 100%;
			max-width: 330px;
			padding: 15px;
			margin: 0 auto;
		}
	</style>
</head>
<body class="text-center">
	<?php include(__DIR__ . '/Navbar.phtml'); ?>
	<form class="notice">
		<h1 class="h3 mb-3 font-weight-normal"><?=$message?></h1>
		<button class="btn btn-lg btn-primary btn-block" onclick="history.back()">Back</button>
	</form>
</body>
</html>