<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Register</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
	<style>
		html,
		body {
			height: 100%;
		}
		.main {
			display: flex;
			align-items: center;
			justify-content: center;
			padding-top: 40px;
			padding-bottom: 40px;
			background-color: #f5f5f5;
		}
		.form-signin {
			width: 100%;
			max-width: 330px;
			padding: 15px;
			margin: 0 auto;
		}
		.form-signin .checkbox {
			font-weight: 400;
		}
		.form-signin .form-control {
			position: relative;
			box-sizing: border-box;
			height: auto;
			padding: 10px;
			font-size: 16px;
		}
		.form-signin .form-control:focus {
			z-index: 2;
		}
		.form-signin input[type="text"] {
			margin-bottom: -1px;
			border-bottom-right-radius: 0;
			border-bottom-left-radius: 0;
		}
		.form-signin input[type="email"] {
			margin-bottom: -1px;
			border-radius: 0;
		}
		.form-signin input[type="password"] {
			margin-bottom: 10px;
			border-top-left-radius: 0;
			border-top-right-radius: 0;
		}
	</style>
</head>
<body>
	<?php include(__DIR__ . '/Navbar.phtml'); ?>
	<div class="main text-center">
		<form class="form-signin" method="POST">
			<h1 class="h3 mb-3 font-weight-normal">Register</h1>
			<label for="inputUser" class="sr-only">Username</label>
			<input name="name" type="text" id="inputUser" class="form-control" placeholder="Username" required autofocus>
			<label for="inputEMail" class="sr-only">EMail</label>
			<input name="email" type="email" id="inputEMail" class="form-control" placeholder="EMail" required autofocus>
			<label for="inputPassword" class="sr-only">Password</label>
			<input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
			<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
			<a href="login" class="btn btn-lg btn-light btn-block">Login</a>
		</form>
	</div>
</body>
</html>